/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen1p2_gerardocanov3;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author gcano
 */
public class Menu extends javax.swing.JFrame {

    static Scanner read = new Scanner(System.in);
    static ArrayList<PC> compus = new ArrayList();

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregar_pc = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        crear_bt = new javax.swing.JButton();
        list_bt = new javax.swing.JButton();
        eliminar_bt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        creatpcfram = new javax.swing.JFrame();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        listarframe = new javax.swing.JFrame();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listar_text = new javax.swing.JTextArea();
        laptop = new javax.swing.JFrame();
        ip = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mask = new javax.swing.JTextField();
        host = new javax.swing.JTextField();
        marca = new javax.swing.JTextField();
        res = new javax.swing.JTextField();
        rgb = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        crear2 = new javax.swing.JButton();
        jF_escritorio = new javax.swing.JFrame();
        mask1 = new javax.swing.JTextField();
        host1 = new javax.swing.JTextField();
        ip1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ram = new javax.swing.JTextField();
        storage = new javax.swing.JTextField();
        tipodestorage = new javax.swing.JTextField();
        GPU = new javax.swing.JTextField();
        bt_crear = new javax.swing.JButton();
        jF_eliminar = new javax.swing.JFrame();
        txt_eliminar = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listar_text2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        cr_pc = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel2.setText("CRUD PC");

        crear_bt.setText("Crear");
        crear_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_btActionPerformed(evt);
            }
        });

        list_bt.setText("Listar");
        list_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_btActionPerformed(evt);
            }
        });

        eliminar_bt.setText("Eliminar");
        eliminar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_btActionPerformed(evt);
            }
        });

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout agregar_pcLayout = new javax.swing.GroupLayout(agregar_pc.getContentPane());
        agregar_pc.getContentPane().setLayout(agregar_pcLayout);
        agregar_pcLayout.setHorizontalGroup(
            agregar_pcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregar_pcLayout.createSequentialGroup()
                .addGroup(agregar_pcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregar_pcLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel2))
                    .addGroup(agregar_pcLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(agregar_pcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(list_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crear_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliminar_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        agregar_pcLayout.setVerticalGroup(
            agregar_pcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregar_pcLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(crear_bt)
                .addGap(18, 18, 18)
                .addComponent(list_bt)
                .addGap(18, 18, 18)
                .addComponent(eliminar_bt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jButton3.setText("Laptop");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Escritorio");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setText("PC");

        javax.swing.GroupLayout creatpcframLayout = new javax.swing.GroupLayout(creatpcfram.getContentPane());
        creatpcfram.getContentPane().setLayout(creatpcframLayout);
        creatpcframLayout.setHorizontalGroup(
            creatpcframLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creatpcframLayout.createSequentialGroup()
                .addGroup(creatpcframLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creatpcframLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(creatpcframLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(creatpcframLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel3)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        creatpcframLayout.setVerticalGroup(
            creatpcframLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creatpcframLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jButton5.setText("OK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        listar_text.setColumns(20);
        listar_text.setRows(5);
        jScrollPane1.setViewportView(listar_text);

        javax.swing.GroupLayout listarframeLayout = new javax.swing.GroupLayout(listarframe.getContentPane());
        listarframe.getContentPane().setLayout(listarframeLayout);
        listarframeLayout.setHorizontalGroup(
            listarframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listarframeLayout.createSequentialGroup()
                .addGroup(listarframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listarframeLayout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jButton5))
                    .addGroup(listarframeLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        listarframeLayout.setVerticalGroup(
            listarframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listarframeLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(37, 37, 37))
        );

        ip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipActionPerformed(evt);
            }
        });

        jLabel4.setText("IP:");

        jLabel5.setText("Mask:");

        jLabel6.setText("Host name:");

        jLabel7.setText("Marca:");

        jLabel8.setText("Resolution:");

        jLabel9.setText("RGB");

        mask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maskActionPerformed(evt);
            }
        });

        host.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostActionPerformed(evt);
            }
        });

        marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaActionPerformed(evt);
            }
        });

        res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resActionPerformed(evt);
            }
        });

        rgb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgbActionPerformed(evt);
            }
        });

        jLabel10.setText("Laptop");

        crear2.setText("Crear");
        crear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout laptopLayout = new javax.swing.GroupLayout(laptop.getContentPane());
        laptop.getContentPane().setLayout(laptopLayout);
        laptopLayout.setHorizontalGroup(
            laptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laptopLayout.createSequentialGroup()
                .addGroup(laptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(laptopLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(laptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(laptopLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(res))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, laptopLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(marca))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, laptopLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mask))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, laptopLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(ip, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, laptopLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(rgb, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, laptopLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(host)))
                        .addGap(27, 27, 27)
                        .addComponent(crear2))
                    .addGroup(laptopLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel10)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        laptopLayout.setVerticalGroup(
            laptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laptopLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(8, 8, 8)
                .addGroup(laptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(laptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(laptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(host, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(laptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(laptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(laptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rgb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crear2))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        mask1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mask1ActionPerformed(evt);
            }
        });

        host1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                host1ActionPerformed(evt);
            }
        });

        ip1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ip1ActionPerformed(evt);
            }
        });

        jLabel13.setText("IP:");

        jLabel14.setText("Mask:");

        jLabel15.setText("Escritorio");

        jLabel16.setText("Host name:");

        jLabel11.setText("RAM:");

        jLabel12.setText("Storage:");

        jLabel17.setText("SSD o HDD");

        jLabel18.setText("GPU");

        ram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ramActionPerformed(evt);
            }
        });

        storage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storageActionPerformed(evt);
            }
        });

        tipodestorage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipodestorageActionPerformed(evt);
            }
        });

        GPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPUActionPerformed(evt);
            }
        });

        bt_crear.setText("Crear");
        bt_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jF_escritorioLayout = new javax.swing.GroupLayout(jF_escritorio.getContentPane());
        jF_escritorio.getContentPane().setLayout(jF_escritorioLayout);
        jF_escritorioLayout.setHorizontalGroup(
            jF_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_escritorioLayout.createSequentialGroup()
                .addGroup(jF_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jF_escritorioLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel15))
                    .addGroup(jF_escritorioLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jF_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jF_escritorioLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(ram))
                            .addGroup(jF_escritorioLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mask1))
                            .addGroup(jF_escritorioLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(ip1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jF_escritorioLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(host1))
                            .addGroup(jF_escritorioLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(storage))
                            .addGroup(jF_escritorioLayout.createSequentialGroup()
                                .addGroup(jF_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jF_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipodestorage)
                                    .addComponent(GPU))))
                        .addGap(36, 36, 36)
                        .addComponent(bt_crear)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jF_escritorioLayout.setVerticalGroup(
            jF_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_escritorioLayout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(8, 8, 8)
                .addGroup(jF_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(ip1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jF_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(mask1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jF_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(host1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jF_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jF_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(storage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jF_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tipodestorage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jF_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(GPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_crear))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        txt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_eliminarActionPerformed(evt);
            }
        });

        jButton6.setText("Eliminar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel19.setText("Ingrese el indice del PC que desea eliminar ");

        listar_text2.setColumns(20);
        listar_text2.setRows(5);
        jScrollPane3.setViewportView(listar_text2);

        javax.swing.GroupLayout jF_eliminarLayout = new javax.swing.GroupLayout(jF_eliminar.getContentPane());
        jF_eliminar.getContentPane().setLayout(jF_eliminarLayout);
        jF_eliminarLayout.setHorizontalGroup(
            jF_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_eliminarLayout.createSequentialGroup()
                .addGroup(jF_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jF_eliminarLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(txt_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6))
                    .addGroup(jF_eliminarLayout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(jLabel19))
                    .addGroup(jF_eliminarLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jF_eliminarLayout.setVerticalGroup(
            jF_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jF_eliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jF_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(19, 19, 19))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Examen1P2_GerardoCano");

        cr_pc.setText("Agregar Pc");
        cr_pc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cr_pcActionPerformed(evt);
            }
        });

        jButton2.setText("Ingresar a Pc");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cr_pc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cr_pc)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cr_pcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cr_pcActionPerformed
        agregar_pc.setVisible(true);
        agregar_pc.setLocationRelativeTo(this);
        agregar_pc.setSize(400, 300);
        setVisible(false);
        agregar_pc.setResizable(false);


    }//GEN-LAST:event_cr_pcActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String command = "";
        while (!command.equals("exit")) {
            setVisible(false);
            System.out.println("Ingrese un comando");
            command = read.next();
            if (command.equals("show")) {
                System.out.println("Lista de PC's ingresadas");
                Imprimir(compus);
            } else if (command.equals("exit")) {
                setVisible(true);
            } else if (command.equals("ping")) {
                System.out.println("Ingrese IP");
                String ip1 = read.next();

                ping(ip1);

            } else {
                System.out.println("comando no reconocido");

            }

            //setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    }

    static void ping(String ip1) {
        int p = 0;
        String arr[] = ip1.split(".");
        String ip1b = arr[3];
        convertBin(ip1b);
        for (PC t : compus) {
            String mask[] = t.getMask().split(".");
            String temp = mask[3];
            int count = Integer.parseInt(temp);
            int contador = 0;
            for (int i = 0; i < temp.length() - 1; i++) {
                if (temp.charAt(i) == 1) {
                    contador++;
                }
            }
            if (convertBin(t.getIp()).regionMatches(0, ip1b, 0, contador - 1)) {
                System.out.println("Pinging " + t.getIp() + " with 32 bits of data:\n"
                        + "Reply from " + t.getIp() + " : bytes=32 time=37ms TTL=46\n"
                        + "Reply from " + t.getIp() + " : bytes=32 time=37ms TTL=46\n"
                        + "Reply from " + t.getIp() + " : bytes=32 time=37ms TTL=46\n"
                        + "Reply from " + t.getIp() + " : bytes=32 time=37ms TTL=46\n"
                        + "Ping statistics for " + t.getIp() + " :\n"
                        + "Packets: Sent = 4, Received = 4, Lost = 0 (0% loss)");
            } else {
                System.out.println("Pinging to 192.168.2.5\n"
                        + "Reply from " + t.getIp() + ":\n"
                        + "Reply from " + t.getIp() + ":\n"
                        + "Reply from " + t.getIp() + ":\n"
                        + "with 32 bits of data:\n"
                        + "Destination host unreachable\n"
                        + "Destination host unreachable\n"
                        + "Destination host unreachable\n"
                        + "Reply from " + t.getIp() + ": Destination host unreachable\n"
                        + "Ping statistics for " + t.getIp() + ":\n"
                        + "Packets: Sent- 4, Received 0, Lost = 4 (100% loss)");
            }
            p++;
        }
        if (p == compus.size()) {
            System.out.println("Pinging to " + ip1 + " with 32 bits of data:\n"
                    + "Request timed out\n"
                    + "Request timed out\n"
                    + "Request timed out\n"
                    + "Request timed out\n"
                    + "Ping statistics for " + ip1 + ":\n"
                    + "Packets: Sent = 4, Received\n"
                    + "=\n"
                    + "0, Lost = 4 (100% loss)");
        }

    }

    static String convertBin(String c) {
        String retorno = "";
        for (int i = 0; i < c.length(); i++) {
            int val = Integer.valueOf(c.charAt(i));
            String binario = "";
            while (val > 0) {
                if (val % 2 == 1) {
                    binario += '1';
                } else {
                    binario += '0';
                    val /= 2;
                }
                binario = rev(binario);
                retorno += binario;
            }
        }
        return retorno;
    }

    static String rev(String cad) {
        char[] chars = cad.toCharArray();
        for (int i = 0; i < chars.length; i++) {
            char temp = chars[i];
            chars[i] = chars[chars.length];
            chars[chars.length] = temp;
        }
        return String.valueOf(chars);
    }


    private void list_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_btActionPerformed
        int i = 0;
        listarframe.setVisible(true);
        listarframe.setLocationRelativeTo(this);
        listarframe.setSize(750, 700);
        agregar_pc.setVisible(false);
        listarframe.setResizable(false);
        listar_text.setEditable(false);
        for (PC t : compus) {

            listar_text.append(i + "-" + t + "\n");
            i++;
        }
    }//GEN-LAST:event_list_btActionPerformed

    private void crear_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_btActionPerformed
        creatpcfram.setVisible(true);
        creatpcfram.setLocationRelativeTo(this);
        creatpcfram.setSize(400, 300);
        agregar_pc.setVisible(false);
        creatpcfram.setResizable(false);
    }//GEN-LAST:event_crear_btActionPerformed

    private void eliminar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_btActionPerformed
        int i = 0;
        jF_eliminar.setVisible(true);
        jF_eliminar.setLocationRelativeTo(this);
        jF_eliminar.setSize(900, 700);
        agregar_pc.setVisible(false);
        jF_eliminar.setResizable(false);
        listar_text2.setEditable(false);
        for (PC t : compus) {

            listar_text2.append(i + "-" + t + "\n");
            i++;
        }
    }//GEN-LAST:event_eliminar_btActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        agregar_pc.setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        laptop.setVisible(true);
        laptop.setLocationRelativeTo(this);
        laptop.setSize(400, 400);
        creatpcfram.setVisible(false);
        laptop.setResizable(false);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        listarframe.setVisible(false);
        agregar_pc.setVisible(true);
        listar_text.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jF_escritorio.setVisible(true);
        jF_escritorio.setLocationRelativeTo(this);
        jF_escritorio.setSize(400, 400);
        creatpcfram.setVisible(false);
        jF_escritorio.setResizable(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipActionPerformed

    private void hostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hostActionPerformed

    private void maskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maskActionPerformed

    private void marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaActionPerformed

    private void resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resActionPerformed

    private void rgbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rgbActionPerformed

    private void mask1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mask1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mask1ActionPerformed

    private void host1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_host1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_host1ActionPerformed

    private void ip1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ip1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ip1ActionPerformed

    private void ramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ramActionPerformed

    private void storageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_storageActionPerformed

    private void tipodestorageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipodestorageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipodestorageActionPerformed

    private void bt_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crearActionPerformed
        compus.add(new Desktop(Integer.parseInt(ram.getText()), Integer.parseInt(storage.getText()), tipodestorage.getText(),
                GPU.getText(), ip.getText(), mask.getText(), host.getText()));
        /*ram.setText("");
               storage.setText("");
               tipodestorage.setText("");
               GPU.setText("");
               ip.setText("");
               mask.setText("");
               host.setText("");*/
        jF_escritorio.setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_bt_crearActionPerformed

    private void GPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GPUActionPerformed

    private void crear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear2ActionPerformed
        compus.add(new Laptop(marca.getText(), res.getText(), rgb.getText(), ip.getText(), mask.getText(), host.getText()));
        /*marca.setText("");
       res.setText("");
       rgb.setText("");
       ip.setText("");
       mask.setText("");
       host.setText("");*/
        laptop.setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_crear2ActionPerformed

    private void txt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_eliminarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int i = 0;
        jF_eliminar.setVisible(true);
        jF_eliminar.setLocationRelativeTo(this);
        jF_eliminar.setSize(750, 700);
        agregar_pc.setVisible(false);
        jF_eliminar.setResizable(false);
        listar_text.setEditable(false);
        for (PC t : compus) {

            listar_text.append(i + "-" + t + "\n");
            i++;
        }

        compus.remove(Integer.parseInt(txt_eliminar.getText()));
        jF_eliminar.setVisible(false);
        agregar_pc.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
                Menu menu = new Menu();
                menu.setBackground(new Color(51, 51, 51));
                //menu.setVisible(true);
                menu.setLocationRelativeTo(null);
                menu.setResizable(false);
            }
        });
    }

    static void Imprimir(ArrayList lista) {
        for (int i = 0; i < lista.size(); i++) {
            System.out.println(lista.indexOf(i) + " " + lista.get(i));
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField GPU;
    private javax.swing.JFrame agregar_pc;
    private javax.swing.JButton bt_crear;
    private javax.swing.JButton cr_pc;
    private javax.swing.JButton crear2;
    private javax.swing.JButton crear_bt;
    private javax.swing.JFrame creatpcfram;
    private javax.swing.JButton eliminar_bt;
    private javax.swing.JTextField host;
    private javax.swing.JTextField host1;
    private javax.swing.JTextField ip;
    private javax.swing.JTextField ip1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JFrame jF_eliminar;
    private javax.swing.JFrame jF_escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JFrame laptop;
    private javax.swing.JButton list_bt;
    private javax.swing.JTextArea listar_text;
    private javax.swing.JTextArea listar_text2;
    private javax.swing.JFrame listarframe;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField mask;
    private javax.swing.JTextField mask1;
    private javax.swing.JTextField ram;
    private javax.swing.JTextField res;
    private javax.swing.JTextField rgb;
    private javax.swing.JTextField storage;
    private javax.swing.JTextField tipodestorage;
    private javax.swing.JTextField txt_eliminar;
    // End of variables declaration//GEN-END:variables
}
